# Generated by Django 4.2.6 on 2023-10-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_availability_product_is_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('s', 'Small'), ('sm', 'Medium'), ('m', 'Large'), ('l', 'Extra Large'), ('xl', 'Double Extra Large')], default='s', max_length=2),
        ),
    ]
