# Generated by Django 4.2.6 on 2023-10-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_brand_name_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_availability',
            field=models.BooleanField(default=True),
        ),
    ]
