# Generated by Django 4.2.6 on 2023-11-23 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_varient_types_remove_product_stock_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_varient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brake', models.CharField(default='Gearless Cycle', max_length=50)),
                ('stock_quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.DeleteModel(
            name='varient_detailes',
        ),
        migrations.DeleteModel(
            name='varient_types',
        ),
    ]
