# Generated by Django 4.2.6 on 2023-11-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_varient_delete_varient_detailes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_varient',
            name='brake',
            field=models.CharField(default='Disc Brake', max_length=50),
        ),
    ]
