# Generated by Django 4.2.6 on 2023-12-06 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_offers'),
        ('product', '0019_alter_product_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.offers'),
        ),
        migrations.DeleteModel(
            name='offers',
        ),
    ]
