# Generated by Django 4.2.4 on 2023-12-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_product_offer_delete_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvarient',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
