# Generated by Django 4.2.4 on 2024-01-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_coupon_max_purchase_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='max_purchase_amount',
        ),
    ]
