# Generated by Django 4.2.4 on 2024-01-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_remove_coupon_used_by_coupon_used_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvarient',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
