# Generated by Django 4.2.4 on 2023-12-15 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_product_offer_delete_offers'),
        ('cart', '0011_alter_wishlist_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product_id',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
    ]
