# Generated by Django 4.2.4 on 2023-12-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_remove_wishlist_product_id_wishlist_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
