# Generated by Django 4.2.4 on 2024-01-05 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_alter_productvarient_price'),
        ('cart', '0016_remove_cart_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productvarient'),
        ),
    ]
