# Generated by Django 4.2.6 on 2023-11-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_remove_payment_payment_id_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Razor Pay', 'Razor Pay'), ('Cash On Delivery', 'Cash On Delivery')], default='Cash On Delivery', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Out For Shipping', 'Out For Shipping'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered')], default='Pending', max_length=150),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
