# Generated by Django 4.2.6 on 2023-11-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_alter_order_payment_method_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Out For Shipping', 'Out For Shipping')], default='Pending', max_length=150),
        ),
    ]
