# Generated by Django 4.2.6 on 2023-12-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_alter_orderitem_status_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='referrel_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Out For Shipping', 'Out For Shipping'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
