# Generated by Django 4.2.6 on 2023-12-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0050_rename_referrel_code_wallet_referral_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Wallet', 'Wallet'), ('Cash On Delivery', 'Cash On Delivery'), ('Razorpay', 'Razorpay')], default='Cash On Delivery', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Out For Shipping', 'Out For Shipping'), ('Shipped', 'Shipped'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=150),
        ),
    ]
