# Generated by Django 4.2.4 on 2023-12-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0069_alter_order_payment_method_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Out For Shipping', 'Out For Shipping'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=150),
        ),
    ]
