# Generated by Django 4.2.6 on 2023-10-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_store', '0003_brand_category_product_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
